# Generated by Django 3.1.4 on 2021-04-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderemail',
            name='send_to',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
