# Generated by Django 3.1.4 on 2021-04-25 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20210424_2107'),
        ('emails', '0002_orderemail_send_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderemail',
            name='ingredients',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='stock.inventoryingredient'
            ),
        ),
    ]
