# Generated by Django 3.1.4 on 2021-04-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_remove_orderemail_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderemail',
            name='text',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
