# Generated by Django 3.1.4 on 2021-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_orderemail_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderemail',
            old_name='text',
            new_name='email_body',
        ),
        migrations.AddField(
            model_name='orderemail',
            name='email_subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
