# Generated by Django 3.1.4 on 2021-04-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_auto_20210425_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderemail',
            name='email_body',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
