# Generated by Django 3.1.4 on 2020-12-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryingredient',
            name='supplier',
            field=models.ManyToManyField(blank=True, null=True, to='supplier.Supplier'),
        ),
    ]
