# Generated by Django 3.1.4 on 2020-12-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20201219_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryingredient',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
