# Generated by Django 3.1.4 on 2021-01-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('stock', '0003_auto_20201222_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryingredient',
            name='supplier',
            field=models.ManyToManyField(blank=True, to='supplier.Supplier'),
        ),
    ]
