# Generated by Django 3.1.4 on 2021-04-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210323_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryingredient',
            name='auto_ordering',
            field=models.BooleanField(default=False),
        ),
    ]
