# Generated by Django 3.1.4 on 2021-04-24 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20210126_0952'),
        ('stock', '0006_inventoryingredient_auto_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryingredient',
            name='supplier',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='supplier.supplier'
            ),
        ),
    ]
