# Generated by Django 3.1.4 on 2021-04-24 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_automatedordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedordering',
            name='email_confirmation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automatedordering',
            name='email_text',
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automatedordering',
            name='record_orders',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
