# Generated by Django 3.1.4 on 2021-04-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_auto_20210425_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedordering',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
