# Generated by Django 3.1.4 on 2021-04-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_automatedordering_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedordering',
            name='subject',
            field=models.CharField(
                blank=True,
                default='Order Placement',
                max_length=200
            ),
        ),
    ]
