# Generated by Django 3.1.4 on 2021-04-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_auto_20210425_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedordering',
            name='email_footer_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='automatedordering',
            name='email_greeting_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='automatedordering',
            name='email_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
