# Generated by Django 3.1.4 on 2021-04-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20210425_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedordering',
            name='email_ingredients_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
