# Generated by Django 3.1.4 on 2021-04-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_automatedordering_email_ingredients_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatedordering',
            name='email_ingredients_text',
        ),
    ]
