# Generated by Django 3.1.4 on 2021-04-25 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_auto_20210425_1315'),
        ('stock', '0023_remove_inventoryingredient_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryingredient',
            name='email_sent',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='ingredients',
                to='emails.orderemail'
            ),
        ),
    ]
