# Generated by Django 3.1.4 on 2021-04-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_auto_20210425_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedordering',
            name='email_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
