# Generated by Django 3.1.4 on 2021-04-27 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_auto_20210425_1315'),
        ('stock', '0028_auto_20210425_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryingredient',
            name='email_sent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='emails.orderemail'),
        ),
    ]
