# Generated by Django 3.1.4 on 2020-12-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dairy', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('vegeterian', models.BooleanField(default=False)),
                ('peanuts', models.BooleanField(default=False)),
                ('fish', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('ingredient', models.ManyToManyField(to='ingredient.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['-name'],
                'unique_together': {('slug', 'parent')},
            },
        ),
    ]
