# Generated by Django 3.1.4 on 2020-12-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAllergenLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='dairy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='egg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fish',
        ),
        migrations.RemoveField(
            model_name='product',
            name='peanuts',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vegan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vegeterian',
        ),
        migrations.AddField(
            model_name='product',
            name='food_allergen_labels',
            field=models.ManyToManyField(to='product.FoodAllergenLabels'),
        ),
    ]
