# Generated by Django 3.1.4 on 2020-12-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201222_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodallergenlabels',
            old_name='value',
            new_name='Tree_nuts',
        ),
        migrations.RemoveField(
            model_name='foodallergenlabels',
            name='name',
        ),
        migrations.AddField(
            model_name='foodallergenlabels',
            name='eggs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodallergenlabels',
            name='fish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodallergenlabels',
            name='milk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodallergenlabels',
            name='peanuts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodallergenlabels',
            name='shellfish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodallergenlabels',
            name='soy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodallergenlabels',
            name='wheat',
            field=models.BooleanField(default=False),
        ),
    ]
