# Generated by Django 3.1.4 on 2020-12-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201222_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='food_allergen_labels',
        ),
        migrations.AddField(
            model_name='foodallergenlabels',
            name='for_product',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
