# Generated by Django 3.1.4 on 2020-12-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201222_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodallergenlabels',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodallergenlabels',
            name='vegeterian',
            field=models.BooleanField(default=False),
        ),
    ]
