# Generated by Django 3.1.4 on 2020-12-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_foodallergenlabels_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='food_allergen_labels',
        ),
        migrations.AddField(
            model_name='product',
            name='food_allergen_labels',
            field=models.ManyToManyField(to='product.FoodAllergenLabels'),
        ),
    ]
