# Generated by Django 3.1.4 on 2020-12-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201223_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
