# Generated by Django 3.1.4 on 2021-04-22 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210422_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='food_allergen_labels',
        ),
        migrations.AddField(
            model_name='product',
            name='food_allergen_labels',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='product.foodallergenlabels'
            ),
        ),
    ]
