# Generated by Django 3.1.4 on 2021-04-24 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0007_auto_20210421_2145'),
        ('product', '0014_auto_20210422_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='food_allergen_labels',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='product.foodallergenlabels'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredient',
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name='product',
                to='ingredient.Ingredient'
            ),
        ),
    ]
