# Generated by Django 3.1.4 on 2021-04-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0007_auto_20210421_2145'),
        ('product', '0015_auto_20210424_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='food_allergen_labels',
        ),
        migrations.AlterField(
            model_name='product',
            name='ingredient',
            field=models.ManyToManyField(blank=True, related_name='product', to='ingredient.Ingredient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.DeleteModel(
            name='FoodAllergenLabels',
        ),
    ]
