# Generated by Django 3.1.4 on 2021-01-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
