# Generated by Django 3.1.4 on 2020-12-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201211_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nin',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
