# Generated by Django 3.1.4 on 2020-12-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20201209_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date_of_bith',
            new_name='date_of_birth',
        ),
    ]
