# Generated by Django 3.1.4 on 2020-12-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='inventory_ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='inventory_ingredient',
            field=models.ManyToManyField(to='stock.InventoryIngredient'),
        ),
    ]
