# Generated by Django 3.1.4 on 2020-12-19 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20201219_1937'),
        ('ingredient', '0002_auto_20201219_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='inventory_ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='inventory_ingredient',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='stock.inventoryingredient'
            ),
            preserve_default=False,
        ),
    ]
