# Generated by Django 3.1.4 on 2021-04-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0004_auto_20201219_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
