# Generated by Django 3.1.4 on 2020-12-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[(
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                                    )
                    ),
                    ('retail_price',
                     models.DecimalField(
                         decimal_places=2,
                         max_digits=4
                                        )
                     ),
                    ('actual_cost',
                     models.DecimalField(
                         decimal_places=2,
                         max_digits=4
                                        )
                     ),
                    ('product',
                     models.ForeignKey(
                         on_delete=django.db.models.deletion.DO_NOTHING,
                         to='product.product'
                                    )
                     ),
                    ],
        ),
    ]
