# Generated by Django 3.1.4 on 2020-12-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderitem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='actual_cost',
        ),
    ]
