# Generated by Django 3.1.4 on 2020-12-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitem', '0002_remove_orderitem_actual_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default='product.name', max_length=30),
        ),
    ]
