# Generated by Django 3.1.4 on 2020-12-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitem', '0003_orderitem_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
