# Generated by Django 3.1.4 on 2020-12-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitem', '0004_auto_20201223_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=30),
        ),
    ]
