# Generated by Django 3.1.4 on 2020-12-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitem', '0005_auto_20201223_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='retail_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
