# Generated by Django 3.1.4 on 2020-12-19 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orderitem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.IntegerField(choices=[(1, 'Takeaway'), (2, 'Have in')])),
                ('order_numer', models.IntegerField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('paid', models.BooleanField()),
                ('payment_method', models.IntegerField(choices=[(1, 'Cash'), (2, 'Card')])),
                ('employee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='orderitem.OrderItem')),
            ],
        ),
    ]
