# Generated by Django 3.1.4 on 2021-04-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(blank=True, choices=[(1, 'Cash'), (2, 'Card')], null=True),
        ),
    ]
